# Generated by Django 3.2.7 on 2021-10-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'diary',
            },
        ),
    ]
